spring:
  application:
    name: ms-user
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
  config:
    import: classpath:application-common.yml

server:
  port: 8081
