services:
  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: sentinel-dashboard
    ports:
      - "8858:8858"
    environment:
      - SENTINEL_DASHBOARD_USERNAME=sentinel
      - SENTINEL_DASHBOARD_PASSWORD=sentinel
    restart: unless-stopped
