package lan.chaos.microservice.user;

import com.baomidou.dynamic.datasource.toolkit.DynamicDataSourceContextHolder;
import lan.chaos.microservice.user.entity.User;
import lan.chaos.microservice.user.entity.UserTag;
import lan.chaos.microservice.user.service.UserService;
import lan.chaos.microservice.user.service.UserTagService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.annotation.Resource;
import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 多数据源集成测试（离线，用 H2 模拟 PG/MySQL 两个命名库）。
 *
 * <p>WHY：验证“同一应用内 @DS 路由到不同数据源且彼此隔离”这一多数据源核心机制，
 * 而不依赖你本机已运行的真实 PG/MySQL。两个 H2 内存库按命名（pg / mysql）隔离，与线上结构一致。
 * 测试用连接信息在 src/test/resources/application.yml（H2 + 关闭 Nacos）。</p>
 *
 * <p>已记录的生产坑（跨方言迁移）：真实 DDL 里 {@code t_user_tag.user_id} 用 {@code BIGINT UNSIGNED}，
 * 但 UNSIGNED 语义在 PG/H2 里不被保留——迁移到 PG 需改用 {@code BIGINT} 或在应用层约束非负。
 * 本测试用 H2 跑通逻辑，上线前请以 {@code sql/demo_ms_*.sql} 为准。</p>
 */
@SpringBootTest
class SqlSliceTest {

    @Resource
    private UserService userService;       // 主库 pg

    @Resource
    private UserTagService userTagService;  // 副库 mysql

    @Resource
    @Qualifier("dataSource")
    private DataSource dynamicDataSource;

    @BeforeEach
    void initSchema() {
        execOn("pg",
                "CREATE TABLE IF NOT EXISTS t_user ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "username VARCHAR(64), nickname VARCHAR(64), age INT, phone VARCHAR(20), "
                        + "created_at TIMESTAMP, updated_at TIMESTAMP, deleted INT DEFAULT 0)");
        execOn("mysql",
                "CREATE TABLE IF NOT EXISTS t_user_tag ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "user_id BIGINT, tag VARCHAR(64), "
                        + "created_at TIMESTAMP, updated_at TIMESTAMP, deleted INT DEFAULT 0)");
    }

    private void execOn(String ds, String sql) {
        DynamicDataSourceContextHolder.push(ds);
        try {
            new JdbcTemplate(dynamicDataSource).execute(sql);
        } finally {
            DynamicDataSourceContextHolder.poll();
        }
    }

    @Test
    void multiDataSource_routesIndependently() {
        // 主库 PG 写用户
        User user = userService.createUser("alice", "Alice", 20, "123");
        assertThat(user.getId()).isNotNull();

        // 副库 MySQL 写标签
        UserTag tag = userTagService.addTag(user.getId(), "vip");
        assertThat(tag.getId()).isNotNull();

        // 隔离验证：各自库的查询互不串
        assertThat(userService.listUsers()).hasSize(1);
        assertThat(userTagService.listTags(user.getId())).hasSize(1);

        // 反向验证：mysql 里的标签行不会出现在 pg 的 user 表里
        assertThat(userService.getUser(user.getId()).getUsername()).isEqualTo("alice");
    }
}
