# source
source.server.address=127.0.0.1
source.server.port=30100
source.server.database=demo
source.server.username=root
source.server.password=<YOUR_PASSWORD>
source.server.server-id=1
source.server.timezone=UTC
# sink
sink.jdbc.url=jdbc:mysql://127.0.0.1:30100/demo?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&useServerPrepStmts=false
sink.jdbc.driver-name=com.mysql.cj.jdbc.Driver
sink.jdbc.username=root
sink.jdbc.password=<YOUR_PASSWORD>
