-- ============================================================
-- PostgreSQL 主库 DDL：库名 demo_ms_pg
-- 执行方式：在 PG 的 demo_ms_pg 库中执行本文件（psql -d demo_ms_pg -f demo_ms_pg_ddl.sql）
-- ============================================================

CREATE TABLE IF NOT EXISTS t_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(64)  NOT NULL,
    nickname   VARCHAR(64)  NOT NULL,
    age        INT,
    phone      VARCHAR(20),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted    INT          NOT NULL DEFAULT 0
);

-- 用户名唯一（仅对未删除行生效，兼容逻辑删除）
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username
    ON t_user (username) WHERE deleted = 0;

COMMENT ON TABLE  t_user IS '用户主表（主数据源 PostgreSQL）';
COMMENT ON COLUMN t_user.deleted IS '逻辑删除：0=未删 1=已删，由 MyBatis-Plus 全局配置自动过滤';
