-- ============================================================
-- PostgreSQL 主库 DDL：库名 demo_ms_pg
-- 执行方式：在 PG 的 demo_ms_pg 库中执行本文件（psql -d demo_ms_pg -f demo_ms_pg_ddl.sql）
-- ============================================================

CREATE TABLE IF NOT EXISTS t_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(64)  NOT NULL,
    nickname   VARCHAR(64)  NOT NULL,
    age        INT,
    phone      VARCHAR(20),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted    INT          NOT NULL DEFAULT 0
);

-- 用户名唯一（仅对未删除行生效，兼容逻辑删除）
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username
    ON t_user (username) WHERE deleted = 0;

COMMENT ON TABLE  t_user IS '用户主表（主数据源 PostgreSQL）';
COMMENT ON COLUMN t_user.deleted IS '逻辑删除：0=未删 1=已删，由 MyBatis-Plus 全局配置自动过滤';

-- ------------------------------------------------------------
-- P3 新增：账户余额表（Seata 分布式事务的「用户侧」分支，写在主库 PG）
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_account (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL UNIQUE,
    balance    NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  t_account IS '用户账户余额（Seata AT 模式分支资源，与订单分属不同库）';
COMMENT ON COLUMN t_account.balance IS '账户余额，单位与订单金额一致（元）';

-- 种子数据：给 user_id=1 预置 1000 元余额，便于直接演示扣减 / 回滚
INSERT INTO t_account (user_id, balance)
VALUES (1, 1000.00)
ON CONFLICT (user_id) DO NOTHING;

-- ------------------------------------------------------------
-- P3 新增：Seata AT 模式 undo_log（每个参与全局事务的库都要有）
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS undo_log (
    id          BIGSERIAL PRIMARY KEY,
    branch_id   BIGINT       NOT NULL,
    xid         VARCHAR(128) NOT NULL,
    context     VARCHAR(128) NOT NULL,
    rollback_info BYTEA      NOT NULL,
    log_status  INT          NOT NULL,
    log_created  TIMESTAMPTZ NOT NULL,
    log_modified TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_undo_log ON undo_log (xid, branch_id);

COMMENT ON TABLE undo_log IS 'Seata AT 模式回滚日志：分支事务提交前记录前后镜像，全局回滚时据此补偿';
